version: '2'

services:
  database:
    build:
      context: ./packages/database
      dockerfile: ./Dockerfile
    container_name: database
    environment:
      POSTGRES_USER: "%%DB_USERNAME%%"
      POSTGRES_PASSWORD: "%%DB_PASSWORD%%"
      DB_NAME: "%%DB_NAME%%"
      POSTGRES_DB: "%%DB_NAME%%"
      PGPORT: "%%DB_PORT%"
  registration-api:
    build:
      context: .
      dockerfile: ./packages/registration-api/Dockerfile
      args:
        PORT: 3000
    command: "yarn start:registration-api"
    container_name: registration-api
    depends_on:
      - database
  authentication-api:
    build:
      context: .
      dockerfile: ./packages/authentication-api/Dockerfile
      args:
        PORT: 3001
    command: "yarn start:authentication-api"
    container_name: authentication-api
    depends_on:
      - database
  transaction-api:
    build:
      context: .
      dockerfile: ./packages/transaction-api/Dockerfile
      args:
        PORT: 3002
    command: "yarn start:transaction-api"
    container_name: transaction-api
    depends_on:
      - database
networks:
  default:
    external:
      name: membership_system