CREATE TABLE T001USER_DETAILS (
  CARD_ID       CHAR(16)     PRIMARY KEY,
  EMPLOYEE_ID   CHAR(10),
  FIRST_NAME    CHAR(20),
  LAST_NAME     CHAR(20),
  EMAIL         CHAR(30),
  MOBILE_NO     CHAR(11),
  DATE_OF_REG   DATE
);


CREATE TABLE T002USER_AUTH (
  CARD_ID       CHAR(16)     PRIMARY KEY    REFERENCES T001USER_DETAILS(CARD_ID),
  PIN           CHAR(4),
  STATUS        CHAR(10),
  ATTEMPTS      CHAR(1)
);


CREATE TABLE T003ACCOUNT_BALANCE (
  CARD_ID       CHAR(16)     PRIMARY KEY,
  BALANCE       DECIMAL(8,2)
);


CREATE TABLE T004ACCOUNT_HISTORY (
  PURCHASE_ID   CHAR(10)     PRIMARY KEY,
  CARD_ID       CHAR(16),
  DESCRIPTION   CHAR(30),
  AMOUNT        DECIMAL(8,2),
  DATE          DATE
);


ALTER TABLE T001USER_DETAILS OWNER TO postgres;
ALTER TABLE T002USER_AUTH OWNER TO postgres;
ALTER TABLE T003ACCOUNT_BALANCE OWNER TO postgres;
ALTER TABLE T004ACCOUNT_HISTORY OWNER TO postgres;